### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [useinsider/insider-gtm-template-main-page#2]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) Please let us know if the submission [https://github.com/gtm-vendor-templates/template-gallery/pull/337](https://github.com/gtm-vendor-templates/template-gallery/pull/337) is duplicate and which one we should consider as both have same code and similar functionality.

**Comment by ugurcann** [comment]
No, it is not duplicate. The code logic is same but assigned values are different.
